name: Setup Foundry

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc
          foundryup
