name: Setup Foundry

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        - name: Install Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        export PATH="$HOME/.foundry/bin:$PATH"
        echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $GITHUB_ENV
        source $HOME/.bashrc
        bash -c "foundryup"
        forge --version
    
        - name: Cache Foundry
        uses: actions/cache@v3
        with:
          path: ~/.foundry
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-foundry-
