name: Run Smart Contract Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          mkdir -p $HOME/.foundry/bin  # Создание каталога для Foundry
          export PATH="$HOME/.foundry/bin:$PATH"
          echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $GITHUB_ENV
          source $HOME/.bashrc || true
          ls -la $HOME/.foundry || echo "⚠️ Ошибка: Папка .foundry отсутствует!"
          ls -la $HOME/.foundry/bin || echo "⚠️ Ошибка: Папка .foundry/bin отсутствует!"
          bash -c "source $HOME/.bashrc && foundryup"
          foundryup || echo "⚠️ Ошибка: Foundryup не найден!"
          forge --version || echo "⚠️ Ошибка: Forge не найден!"
      
      

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug workspace
        run: |
          echo "🔍 Checking workspace..."
          ls -la
          pwd

      - name: Run Web3.py tests
        run: |
          if [ -d "test-cases" ]; then
            pytest test-cases/
          else
            echo "⚠️ Ошибка: Папка test-cases не найдена!"
            exit 1
          fi

      - name: Run Foundry tests
        run: forge test -vvv
