name: Run Smart Contract Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          echo "🔽 upload Foundry..."
          curl -L https://foundry.paradigm.xyz | bash

          echo "🔄 create directory Foundry..."
          mkdir -p $HOME/.foundry/bin
          mv $HOME/.foundry/bin/* $HOME/.foundry/

          echo "🔧 install Foundry..."
          export PATH="$HOME/.foundry/bin:$PATH"
          echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $GITHUB_ENV
          source $HOME/.bashrc || true
          foundryup || echo "⚠️ Error: Foundryup don't found!"
          forge --version || echo "⚠️ Error: Forge absent!"

      - name: Debug workspace
        run: |
          echo "🔍 checking directory .foundry..."
          ls -la $HOME/.foundry || echo "⚠️  .foundry absent!"
          echo "🔍 Проверяем директорию bin..."
          ls -la $HOME/.foundry/bin || echo "⚠️ П .foundry/bin absent!"
          echo "🔍 Present PATH: $PATH"

      - name: Run Foundry tests
        run: forge test -vvv
