name: Run Smart Contract Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $GITHUB_ENV
          bash -c "source $HOME/.bashrc && foundryup"
          foundryup
          forge install
          forge --version
      

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Web3.py tests
        run: pytest test-cases/

      - name: Run Foundry tests
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          forge test -vvv
