name: Run Smart Contract Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          mkdir -p $HOME/.foundry/bin
          export PATH="$HOME/.foundry/bin:$PATH"
          echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $GITHUB_ENV
          source $HOME/.bashrc || true
          ls -la $HOME/.foundry/bin || echo "⚠️ Ошибка: Папка .foundry/bin отсутствует!"
          foundryup || echo "⚠️ Ошибка: Foundryup не найден!"
          forge --version || echo "⚠️ Ошибка: Forge не найден!"

      - name: Debug workspace
        run: |
          echo "🔍 Проверяем файлы..."
          ls -la
          echo "🔍 Проверяем директорию .foundry..."
          ls -la $HOME/.foundry
          echo "🔍 Проверяем директорию bin..."
          ls -la $HOME/.foundry/bin
          echo "🔍 Текущий PATH: $PATH"

      - name: Run Foundry tests
        run: forge test -vvv
