name: Run Smart Contract Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          echo "🔽 Загружаем Foundry..."
          curl -L https://foundry.paradigm.xyz | bash

          echo "🔄 Создаём директорию Foundry..."
          mkdir -p $HOME/.foundry/bin
          mv $HOME/.foundry/bin/* $HOME/.foundry/

          echo "🔧 Устанавливаем Foundry..."
          export PATH="$HOME/.foundry/bin:$PATH"
          echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $GITHUB_ENV
          source $HOME/.bashrc || true
          foundryup || echo "⚠️ Ошибка: Foundryup не найден!"
          forge --version || echo "⚠️ Ошибка: Forge не найден!"

      - name: Debug workspace
        run: |
          echo "🔍 Проверяем директорию .foundry..."
          ls -la $HOME/.foundry || echo "⚠️ Папка .foundry отсутствует!"
          echo "🔍 Проверяем директорию bin..."
          ls -la $HOME/.foundry/bin || echo "⚠️ Папка .foundry/bin отсутствует!"
          echo "🔍 Текущий PATH: $PATH"

      - name: Run Foundry tests
        run: forge test -vvv
