name: Run Smart Contract Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          echo 'export PATH="$HOME/.foundry/bin:$PATH"' >> $GITHUB_ENV
          source $HOME/.bashrc || true
          foundryup
          forge --version || echo "⚠️ Ошибка: Forge не найден!"

      - name: Debug workspace
        run: |
          echo "🔍 Проверяем файлы..."
          ls -la
          echo "🔍 Проверяем установку Foundry..."
          ls -la $HOME/.foundry || echo "⚠️ Ошибка: Папка .foundry отсутствует!"
          ls -la $HOME/.foundry/bin || echo "⚠️ Ошибка: Папка .foundry/bin отсутствует!"

      - name: Run Foundry tests
        run: forge test -vvv
